### PR TITLE
[JENKINS-55411] Whitelist DateTimeFormatter.ofPattern(String)

### PR DESCRIPTION
**Pull request by zhogov**
Whitelisted [DateTimeFormatter.ofPattern(String)](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html#ofPattern-java.lang.String-) since currently we have only set of constants whitelisted (BASIC_ISO_DATE, ISO_DATE_TIME...) that doesn't cover all real-life use cases

### CODE REVIEW

**Comment by zhogov** [comment]
I have no idea why it shows 3 commits, I pushed only one

**Comment by zhogov** [comment]
Oh, I see, because of force-push in master by **abayer**

**Comment by dwnusbaum** [comment]
I think the problem is that your commit was based on commits in `master` that were force-pushed over for the recent security release. In other words, you built on top of the merge commit for https://github.com/jenkinsci/script-security-plugin/pull/234, but that commit no longer exists. If you rebase onto 6ff803006d (current `master`) then the extra commits should go away.

**Comment by dwnusbaum** [comment]
Superseded by #237.

**Pull request closed without merging**
