### PR TITLE
[JENKINS-41247] Include test for previously approved blacklisted signatures

### PR DESCRIPTION
**Pull request by varyvol**
[JENKINS-41247](https://issues.jenkins-ci.org/browse/JENKINS-41247)

Include test coverage for previously approved signatures that have been blacklisted.

@reviewbybees @jglick

### CODE REVIEW

**Comment by varyvol** [comment]
To ease the review, the content of the scriptApproval.xml file contained in ScriptApprovalTest.zip is the following:

`<?xml version='1.0' encoding='UTF-8'?>
<scriptApproval plugin="script-security@1.24">
  <approvedScriptHashes>
    <string>837ca1408f808d50b53be635b8c5dc41b806ee8c</string>
  </approvedScriptHashes>
  <approvedSignatures>
    <string>staticMethod hudson.model.User current</string>
  </approvedSignatures>
  <aclApprovedSignatures/>
  <approvedClasspathEntries/>
  <pendingScripts/>
  <pendingSignatures/>
  <pendingClasspathEntries/>
</scriptApproval>`

**Comment by andresrc** [comment]
If the approved hash is not needed we can remove it. LGTM otherwise.

**Comment by varyvol** [comment]
@andresrc verified it is not needed and removed.

**Comment by mafraba** [comment]
LGTM 🐝

**Comment by jglick** [comment]
Amends #94 I guess.

**Pull request merged**
