### PR TITLE
allow: method java.util.regex.Matcher replaceAll java.lang.String

### PR DESCRIPTION
**Pull request by aheritier**

### CODE REVIEW

**Comment by aheritier** [comment]
@reviewbybees

**Comment by imod** [comment]
:+1:

**Comment by andresrc** [comment]
:bee:

**Comment by mslusarczyk** [comment]
🐝  after org.jenkinsci.plugins.scriptsecurity.sandbox.whitelists.GenericWhitelistTest is fixed

**Comment by aheritier** [comment]
rhooooo my bad!!! Thanks a lot @mslusarczyk I didn't see the test to validate the order. I should be fixed (I tested locally this time)

**Comment by aheritier** [comment]
@reviewbybees done
If a maintainer can review and merge please (cc @jglick )

**Comment by olivergondza** [comment]
I wonder if there is some policy in place in case of accepting whitelist entries or I can go ahead and merge anything with enough emoticons on it.

**Comment by aheritier** [comment]
good question @olivergondza I don't think there is a policy. Maybe the only policy we should do is to ask to the security team to review changes done before each release ?

**Comment by aheritier** [comment]
@reviewbybees done
ping @jenkinsci/code-reviewers

**Comment by jglick** [comment]
> if there is some policy in place in case of accepting whitelist entries

I merge PRs to this plugin as soon as I see them.

**Pull request merged**
