### PR TITLE
No need to override `reuseForks`

### PR DESCRIPTION
**Pull request by jglick**
As of https://github.com/jenkinsci/plugin-pom/pull/453. Supersedes #370.

### CODE REVIEW

**Review by car-roll — APPROVED** [review]

**Comment by car-roll** [comment]
@jtnord can you review? I don't have write access

**Comment by jglick** [comment]
> I don't have write access

Hmm, acc. to https://github.com/jenkins-infra/repository-permissions-updater/blob/89a048542cdbb247371838d12c805929ea7da94d/permissions/plugin-script-security.yml#L15 you should. @timja et al.?

**Comment by timja** [comment]
fixed

**Comment by car-roll** [comment]
Sorry, I meant I don't have GitHub access

**Comment by timja** [comment]
:shipit: 

image

**Comment by timja** [comment]
> Welps, that's strange, now I see the merge button 🙃

GitHub's UI isn't very live, refresh is often needed or even a couple

**Pull request merged**
