### PR TITLE
Fix broken icon on modern Jenkins versions

### PR DESCRIPTION
**Pull request by NotMyFault**
Fixes [JENKINS-67771](https://issues.jenkins.io/browse/JENKINS-67771)

Probably best to merge it after https://github.com/jenkinsci/script-security-plugin/pull/373, because this change either requires 2.319.x or newer.

- [X] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [X] Ensure that the pull request title represents the desired changelog entry
- [X] Please describe what you did
- [X] Link to relevant issues in GitHub or Jira
- [X] Link to relevant pull requests, esp. upstream and downstream changes
- [X] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by NotMyFault** [comment]
Heyo @car-roll, 

now that you have have merged https://github.com/jenkinsci/script-security-plugin/pull/373, do you mind taking a look at this PR too? The requirements are now met.
Thanks in advance :)

**Comment by NotMyFault** [comment]
Could you try to trigger the release workflow again please? GitHub actions had an issue with drafts yesterday.
See https://groups.google.com/g/jenkinsci-dev/c/110lPg1O2u0 for reference.

**Comment by car-roll** [comment]
hmm, looks like there are still some issues

**Comment by car-roll** [comment]
yeah, looks okay now. I bunch of dependabot actions went through.

**Pull request merged**
