### PR TITLE
Update plugin parent POM; use plugin BOM

### PR DESCRIPTION
**Pull request by basil**
Supercedes #338, #341, and #343. Adapts to jenkinsci/bom#505.

### CODE REVIEW

**Review by bitwiseman — APPROVED** [review]

**Comment by basil** [comment]
Thanks for the quick review! I just realized I forgot to update `git-changelist-maven-extension`, so I pushed another commit that does that. Feel free to squash merge this if desired.

**Review by dwnusbaum — APPROVED** [review]

**Review by res0nance — APPROVED** [review]

**Review by jglick — APPROVED** [review]

**Comment by basil** [comment]
> Do you know why the build of the `sample-plugin` did not catch this?

Not sure; I just upgraded and hit the same issue as you and Mark. This patch is all I can offer at the moment.

**Comment by jglick** [comment]
Can reproduce via

```diff
diff --git sample-plugin/pom.xml sample-plugin/pom.xml
index 434520e..68c7698 100644
--- sample-plugin/pom.xml
+++ sample-plugin/pom.xml
@@ -95,6 +95,11 @@
             <groupId>org.jenkins-ci.plugins.workflow</groupId>
             <artifactId>workflow-step-api</artifactId>
         </dependency>
+        <dependency>
+            <groupId>org.jenkins-ci.plugins</groupId>
+            <artifactId>script-security</artifactId>
+            <scope>test</scope>
+        </dependency>
         <dependency>
             <groupId>org.jenkins-ci.plugins.workflow</groupId>
             <artifactId>workflow-basic-steps</artifactId>
```

as

```
[WARNING] Rule 5: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:
Failed while enforcing RequireUpperBoundDeps. The error(s) are [
Require upper bound dependencies error for com.github.ben-manes.caffeine:caffeine:2.8.8 paths to dependency are:
+-io.jenkins.tools.bom:sample:999999-SNAPSHOT
  +-org.jenkins-ci.plugins:script-security:1.76
    +-com.github.ben-manes.caffeine:caffeine:2.8.8
and
+-io.jenkins.tools.bom:sample:999999-SNAPSHOT
  +-io.jenkins:configuration-as-code:1.51
    +-io.jenkins.plugins:caffeine-api:2.9.1-23.v51c4e2c879c8
      +-com.github.ben-manes.caffeine:caffeine:2.9.1
]
```

Maven rather arbitrarily picks up the “closest” transitive dependency, even if it is older than something “further”. Not much we can do to defend against this generally, I think; whether you will hit this regression from https://github.com/jenkinsci/bom/pull/504 will vary according to seemingly minor details of how your POM is arranged.

**Comment by jglick** [comment]
Basically we need to use https://github.com/jenkinsci/plugin-pom/blob/386ed627e6fe912493a0e535ca200619ef7e99ed/pom.xml#L536-L543 to work around the fact that the way Maven picks transitive dependency versions is ridiculous.

**Pull request merged**
