### PR TITLE
MetaClass delegate handling

### PR DESCRIPTION
**Pull request by jglick**
Found that a trick used to bind synthetic methods to existing classes was being rejected by the sandbox. Here it is assumed that the closure itself is implicitly whitelisted; `Whitelist` does not have any mechanism for listing non-Java “methods” like this.

@reviewbybees esp. @kohsuke

### CODE REVIEW

**Comment by kohsuke** [comment]
IIUC, this allows any closure invocation, such as those obtained via method pointer operation. Is this safe? Looking at the test case, it seems like this case should be checked against `String.getAnswer()`  method.

:bee: so as not to block Jesse in case I got it all wrong.

**Comment by jglick** [comment]
I could check whether it applies also to method pointers. I am not too concerned even if it does, since `DefaultGroovyMethod.getMetaClass` and `MetaClass.setProperty` will still be rejected, so you could not use that to mount an attack—a trusted source would have to have installed the metamethod to begin with. Or are you saying something else @kohsuke?

**Comment by kohsuke** [comment]
I think I confused myself with earlier question about allowing any closure invocation, so I take that back.

**Comment by andresrc** [comment]
:bee:

**Comment by kohsuke** [comment]
I consider my previous :bee: standing, but here's another one because process!!

:bee:

**Pull request merged**
