### PR TITLE
[FIXED JENKINS-41797] Make sure wrapper WeakHashMap will not be manipulated concurrenlty

### PR DESCRIPTION
**Pull request by olivergondza**
[JENKINS-41797](https://issues.jenkins-ci.org/browse/JENKINS-41797)

### CODE REVIEW

**Comment by olivergondza** [comment]
I have started to see this repeatedly after moving an instance to Java 8. @jglick, as an author, can you have a look so we can get this released ASAP? Thanks.

**Comment by olivergondza** [comment]
@reviewbybees

**Comment by olivergondza** [comment]
> ...other than perhaps WeakHashMap occasionally going into an endless loop if mutated concurrently.

Yes that is the problem and it is a pretty severe one if it prevents Jenkins from loading the jobs altogether. This classifies as blocker IIRC.

Ad proper synchronization, I guess there are similar situations when different `WeakHashMap` operations can cause something similar. I am not familiar enough with the code to be confident about wrapping that into synchronized collection.

**Comment by olivergondza** [comment]
> What makes you think synchronizing just this access is going to solve the problem?

What is happening IMO is that 2 loading threads get a race condition on one of the singleton whitelists and spin forever. The rest of the threads get there sooner or later and join the same party. If the access get synchronized, the race will never cause the livelock of the 2 threads.

**Comment by olivergondza** [comment]
@jglick, so what do you suggest? Synchronize access to all the fields (as their consistency is not guaranteed with current implementation) which would resolve this bug as well?

**Comment by jglick** [comment]
> so what do you suggest?

I think I suggested a fix above.

Certainly I could write that myself, but you seem to be the only one to have observed this issue (or at least the only one to report it), so I guess you could try a snapshot.

**Comment by olivergondza** [comment]
[WS ignoring diff](https://github.com/jenkinsci/script-security-plugin/pull/106/files?w=1). Synchronizing on prominent final field instead of `this` not to expose the monitor.

**Comment by olivergondza** [comment]
@jenkinsci/code-reviewers, please have a look.

**Comment by olivergondza** [comment]
> This pull request originates from a CloudBees employee.

Huh? That must have been one heck of a weekend ...

**Comment by jglick** [comment]
Hmm, the bots must be crazy.

**Pull request merged**
