### PR TITLE
[JENKINS-42091] Add some needed methods of JSON superclass

### PR DESCRIPTION
**Pull request by nfalco79**
This PR is suggest by @rsandell [here](https://github.com/jenkinsci/pipeline-utility-steps-plugin/pull/22)

### CODE REVIEW

**Comment by nfalco79** [comment]
Move to correct place so _sanity_ test pass

**Comment by nfalco79** [comment]
The main reson of this PR is that when I get a JSON from JsonSlurper 
`def json = new JsonSlurper().from(file)`
or from step readJSON 
`def json = readJSON file: 'jsonFile'`
I do not know if the json instance is JSONObject or a JSONArray so i have to call isArray() method to understand how to access values or an exception is throwed.
```
if (json.isArray()) {
   echo json[0]
} else {
   echo json.key
}
```

I add to whitelist also JSON.size() because is a convenient method in case of JSONArray

**Comment by nfalco79** [comment]
@reviewbybees

**Comment by nfalco79** [comment]
maybe I used a wrong annotation :P

**Comment by jglick** [comment]
Do not use `JsonSlurper` BTW.

**Pull request merged**
