### PR TITLE
Add break tag in ScriptSecurity plugin page

### PR DESCRIPTION
**Pull request by michalrys**
Resolves: https://issues.jenkins.io/browse/JENKINS-72264

### Testing done
There is no need for test it because this is very simple issue - just adding missing BR tag between 271 and 272 lines - according to https://issues.jenkins.io/browse/JENKINS-72264 -> description and last comment of @MarkEWaite.

### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by jglick** [comment]
Before and after screenshots would be appreciated. Just use `mvn hpi:run`.

**Comment by yyosha** [comment]
Before:
image

After:
image

Changes were made on local client. Not on server!

**Review by MarkEWaite — APPROVED** [review]

**Comment by jglick** [comment]
Ah OK, much clearer now, thanks!

**Comment by michalrys** [comment]
Oh great, thank you for pictures ;)

**Pull request merged**
