### PR TITLE
Add Calendar and DateFormat members to generic whitelist

### PR DESCRIPTION
**Pull request by cidermole**
Trying again, since original doesn't seem to build anymore on Jenkins, due to forced pushes.

* Add java.util.Calendar members to the generic whitelist
* Add java.text.DateFormat (for SimpleDateFormat) members to the generic whitelist

More can be generated using https://gist.github.com/cidermole/836abd1c12a59830465e89cba4492ecf

### CODE REVIEW

**Comment by bitwiseman** [comment]
@dwnusbaum Could we automatically check for the stderr output you're talking about?

**Comment by dwnusbaum** [comment]
@bitwiseman We could, see https://github.com/jenkinsci/script-security-plugin/pull/268#issuecomment-537489698, it's just a matter of having time to work on it.

**Comment by dwnusbaum** [comment]
@cidermole if you merge master into your branch, the output I mentioned will be incorporated into the CI build so we'll know if any of the new signatures are typo'd without you having to check `stderr` manually.

**Comment by dwnusbaum** [comment]
I had a chance to test this PR, and noticed a few things that could be improved, see https://github.com/jenkinsci/script-security-plugin/pull/295, so I am going to close this. Thanks!

**Pull request closed without merging**
