### PR TITLE
[JENKINS-28154] Reproduce in unittest

### PR DESCRIPTION
**Pull request by olivergondza**
[JENKINS-28154](https://issues.jenkins-ci.org/browse/JENKINS-28154)

I tried to exercise as much operators/keywords as possible, though only `in` (membership operator, not foreach separator) seems to cause this problem. I also whitelisted  some methods.

### CODE REVIEW

**Comment by olivergondza** [comment]
https://github.com/kohsuke/groovy-sandbox/pull/26

**Comment by jglick** [comment]
If you mark this

```java
@Ignore("TODO JENKINS-28154")
```

I would consider it mergeable.

**Comment by olivergondza** [comment]
It can be merged as is after https://github.com/kohsuke/groovy-sandbox/pull/26 is integrated :wink:.

**Comment by jglick** [comment]
Once #22 is merged, you should merge with `master` and this will get rechecked.

**Comment by jglick** [comment]
BTW it was not necessary to close this, as when #23 is merged, GH will automatically display this as merged as well (since the branch head would be an ancestor of the `master` branch head).

**Pull request closed without merging**
