### PR TITLE
whitelist locales and locale specific up/lower case

### PR DESCRIPTION
**Pull request by jtnord**
@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
:bee:

**Comment by rsandell** [comment]
No Swedish :'( 

:bee:

**Comment by jtnord** [comment]
@reviewbybees done

**Comment by amuniz** [comment]
> No Swedish :'(

And no Spanish... :crying_cat_face:

**Comment by jtnord** [comment]
blah blah blah

**Comment by amuniz** [comment]
@jtnord :smile: I was really complaining to Oracle, not you.

**Pull request merged**
