### PR TITLE
Permit access to the messages of exceptions.

### PR DESCRIPTION
**Pull request by dothebart**
Currently Scripts may catch exceptions, but not fetch their messages for i.e. putting it into error report mails.

### CODE REVIEW

**Comment by dothebart** [comment]
ok, I was trying to find a sensitive place. is it alphabetic order?

**Comment by dothebart** [comment]
it seems that jenkins mixes commits to pr #85 into the tests it does? seems like a bug in jenkins to me?

**Comment by jglick** [comment]
No, your commit just broke an existing test.

**Comment by dothebart** [comment]
Ah, Ic. thanks for the assistance.

**Pull request merged**
