### PR TITLE
[JENKINS-55303] Skip Memory test on JVM greater than Java 8

### PR DESCRIPTION
**Pull request by alecharp**
[JENKINS-55303](https://issues.jenkins-ci.org/browse/JENKINS-55303)

Based on recommendation by @dwnusbaum to prevent false negative on tests on Java9+.

@jenkinsci/java11-support

### CODE REVIEW

**Comment by batmat** [comment]
We should probably also file a PR to build this on various JDKs.

**Comment by alecharp** [comment]
I agree @batmat but if I do it,it won't be used to build the PR..

**Comment by batmat** [comment]
Yeah, no worries. I'm aware, that's also the reason I've not myself yet scripted something to file such a PR on a bunch of plugins.

**Comment by alecharp** [comment]
@dwnusbaum @rsandell Could we merge this and change the `Jenkinsfile` to 

```
coreJdk11Version="2.164"

buildPlugin(configurations: [
  [ platform: "linux", jdk: "8", jenkins: null ],
  [ platform: "windows", jdk: "8", jenkins: null ],
  [ platform: "linux", jdk: "8", jenkins: coreJdk11Version, javaLevel: "8" ],
  [ platform: "windows", jdk: "8", jenkins: coreJdk11Version, javaLevel: "8" ],
  [ platform: "linux", jdk: "11", jenkins: coreJdk11Version, javaLevel: "8" ],
  [ platform: "windows", jdk: "11", jenkins: coreJdk11Version, javaLevel: "8" ]
])
```

this way we would have Java 11 build on the plugin as well.
Thanks.

**Comment by abayer** [comment]
@alecharp - feel free to update with the Jenkinsfile change and then I'll merge.

**Comment by alecharp** [comment]
done. Thanks @abayer !

**Comment by alecharp** [comment]
Build is now broken because of the missing javadoc required by Java 11. I'll create a followup PR to fix master.

**Pull request merged**
