### PR TITLE
More whitelisted methods (dates)

### PR DESCRIPTION
**Pull request by darxriggs**

### CODE REVIEW

**Comment by darxriggs** [comment]
ci.jenkins.io had some hiccups.

**Comment by darxriggs** [comment]
Yes, I checked that. There are no new "Cannot check validity of ..." entries for `GenericWhitelistTest` and `StaticWhitelistTest`. This should be automated even more, taking the Groovy version into account with which the tests are running.

**Comment by darxriggs** [comment]
still hiccups on ci.jenkins.io

**Comment by darxriggs** [comment]
ci.jenkins.io always failing on cleanup. I'll try with a rebase on master.

**Comment by darxriggs** [comment]
@dwnusbaum now we have a successful build.

**Comment by dwnusbaum** [comment]
> There are no new "Cannot check validity of ..." entries for GenericWhitelistTest and StaticWhitelistTest. This should be automated even more, taking the Groovy version into account with which the tests are running.

Yes, ideally we'd just fail the tests when something is wrong, but we'd need to special-case some entries, see https://github.com/jenkinsci/script-security-plugin/pull/268#issuecomment-537489698.

**Pull request merged**
