### PR TITLE
Allow selected scripts to be removed from approvals

### PR DESCRIPTION
**Pull request by EricBartusch**
There are times where we want to remove a few approved scripts, and removing everything seems a bit excessive.  Editing the scriptApproval.xml requires a restart of Jenkins which causes an interruption during working hours and feels a little hacky.

I changed the tag where the approvals are listed from a textarea to a table.  With the table, users can select rows and hit the "clear selected" button to remove the highlighted rows.  This change required a revamp of the updateApprovedSignatures javascript method.  The body of the table must be recreated instead of the value of a textarea.  Also, the acl/dangerous approvals will conditionally either have just a table tag if there are no approvals to go in the box.  The description text above the tables will always appear.

Related issue:
https://issues.jenkins-ci.org/browse/JENKINS-22660

Kind of related issues though they were worked around:
https://issues.jenkins-ci.org/browse/JENKINS-31344
https://issues.jenkins-ci.org/browse/JENKINS-38352

### CODE REVIEW

**Comment by AndreasBS** [comment]
Thank you for making this. I would really like to use this functionality, but would prefer not running this plugin from a fork. Any chance of this PR being merged any time soon?

**Comment by EricBartusch** [comment]
Hey @AndreasBS, I'm guessing that this PR won't be merged.  From what I understand, Jenkins won't need the script security plugin in the future.  If you go to the 24th slide [here](https://schd.ws/hosted_files/devopsworldjenkinsworld2018/cd/JW_DW%20San%20Francisco%20-%20Solving%20Pipeline%20Performance%20Problems%20with%20Systems%20Theory%20-%20Sam%20Van%20Oort%20-%20Samuel%20Van%20Oort.pdf), there are some slides about the new Jenkins Pipeline Engine.  Since my PR is a pretty big change to how the plugin currently works, I can imagine it's just not worth merging.

**Comment by AndreasBS** [comment]
Hi @EricBartusch, that's too bad. Thanks for the effort and the fast reply. At least the new pipeline looks promising, so I guess we'll just wait for that.

**Comment by bitwiseman** [comment]
@EricBartusch That future may or may not be a reality.  
Could you merge master into this PR?  That will let folks get an incremental build from the CI system and take this for a spin.

**Comment by bitwiseman** [comment]
@EricBartusch Thanks for the quick turn around.

**Comment by darxriggs** [comment]
Can we make this feature happen somehow?

**Comment by jglick** [comment]
Is this covered by #300?

**Comment by EricBartusch** [comment]
Looks like it, and it looks a ton better than what I had here.

**Comment by jglick** [comment]
Closing, pending someone with time to properly review proposed UI improvements.

**Pull request closed without merging**
